import { cp, mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import tailwindcss from "@tailwindcss/vite";
import { defineConfig, type Plugin } from "vite";

const staticEntries = ["404.html", "CNAME", ".nojekyll", "manifest.webmanifest", "assets", "js"];

async function filesUnder(directory: string, prefix = ""): Promise<string[]> {
  const output: string[] = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const relative = join(prefix, entry.name);
    if (entry.isDirectory()) output.push(...await filesUnder(join(directory, entry.name), relative));
    else output.push(relative);
  }
  return output;
}

function workspaceStaticAssets(): Plugin {
  return {
    name: "workspace-static-assets",
    apply: "build",
    async closeBundle() {
      await mkdir("dist", { recursive: true });
      for (const entry of staticEntries) await cp(entry, join("dist", entry), { recursive: true });
      const generatedAssets = (await filesUnder("dist/assets"))
        .filter(file => /\.(?:js|css|woff2?|png|svg)$/.test(file))
        .map(file => `/assets/${file.replaceAll("\\", "/")}`);
      const applicationModules = (await filesUnder("dist/js"))
        .filter(file => file.endsWith(".js"))
        .map(file => `/js/${file.replaceAll("\\", "/")}`);
      const source = await readFile("sw.js", "utf8");
      const serviceWorker = source.replace("const BUILD_ASSETS = []; // @vite-assets", `const BUILD_ASSETS = ${JSON.stringify([...generatedAssets,...applicationModules])}; // generated by Vite`);
      await writeFile("dist/sw.js", serviceWorker);
    }
  };
}

export default defineConfig({
  plugins: [tailwindcss(), workspaceStaticAssets()],
  build: {
    target: "es2022",
    sourcemap: true,
    manifest: true,
    cssCodeSplit: false,
    rollupOptions: {
      output: {
        entryFileNames: "assets/workspace-[hash].js",
        chunkFileNames: "assets/module-[hash].js",
        assetFileNames: "assets/workspace-[hash][extname]"
      }
    }
  }
});
