import { mailbox,mailboxThread,updateMailboxMessage,sendMail,mailboxTemplates,mailboxStyle,saveMailboxStyle } from "../api.js";
import { h,pageHeader,card,button,toolbar,modal,field,input,textarea,toast,errorMessage,emptyState,formatDate,badge } from "../ui.js";

const folders=["INBOX","SENT","DRAFTS","STARRED","ARCHIVED","TRASH"];
function addresses(value){return String(value||"").split(/[;,]/).map(v=>v.trim()).filter(Boolean)}
function mailTitle(m){return m.subject||"(Sans objet)"} function sender(m){return m.fromName||m.from_name||m.fromEmail||m.from_email||"Expéditeur"}
function bodyOf(m){return m.body||m.textBody||m.text_body||m.preview||""}
function mailDate(m){return m.receivedAt||m.received_at||m.sentAt||m.sent_at||m.createdAt||m.created_at}
function compose(reload,replyTo=null){
  const to=input(replyTo?.fromEmail||replyTo?.from_email||"");const subject=input(replyTo?`Re: ${String(replyTo.subject||"").replace(/^Re:\s*/i,"")}`:"");const body=textarea("");
  modal({title:replyTo?"Répondre":"Nouveau message",content:h("div",{class:"form"},field("À",to),field("Objet",subject),field("Message",body)),wide:true,actions:[{label:"Envoyer",kind:"primary",icon:"send",onClick:async close=>{try{const text=body.value.trim();await sendMail({to:addresses(to.value),cc:[],bcc:[],subject:subject.value.trim(),body:text,blocks:[{id:crypto.randomUUID(),kind:"PARAGRAPH",text,url:"",alternativeText:""}],...(replyTo?.providerThreadID?{providerThreadID:replyTo.providerThreadID}:{})});toast("E-mail envoyé");close();reload()}catch(e){toast(errorMessage(e),"error",6000)}}}]});
}
async function mailboxMain(){
  const root=h("div");let folder="INBOX",query="",selected=null;const listHost=h("div"),detailHost=h("div");
  root.append(pageHeader({eyebrow:"Communication",title:"E-mails",subtitle:"Boîte Workspace connectée aux services de messagerie externes.",actions:[button("Nouveau message",{kind:"primary",iconName:"add",onClick:()=>compose(load)})]}),h("div",{class:"subnav"},...folders.map(f=>button(f,{small:true,onClick:()=>{folder=f;load()}}))),h("div",{class:"split-view"},card("Boîte mail","Messages synchronisés.",listHost,{iconName:"mail"}),card("Lecture","Sélectionnez une conversation.",detailHost,{iconName:"document"})));
  const open=async m=>{selected=m;try{const data=await mailboxThread(m.id);const thread=data.messages||[];detailHost.replaceChildren(h("div",{},h("div",{class:"toolbar"},button("Répondre",{kind:"primary",iconName:"send",onClick:()=>compose(load,thread.at(-1)||m)}),button(m.isStarred?"Retirer l’étoile":"Favori",{iconName:"star",onClick:async()=>{await updateMailboxMessage(m.id,{isStarred:!m.isStarred});load()}}),button("Archiver",{iconName:"archive",onClick:async()=>{await updateMailboxMessage(m.id,{folder:"ARCHIVED"});load()}})),...thread.map(msg=>h("article",{class:"card",style:{marginBottom:"10px"}},h("div",{class:"row-title",text:`${sender(msg)} · ${mailTitle(msg)}`}),h("div",{class:"row-sub",text:formatDate(mailDate(msg))}),h("div",{class:"mail-body",style:{marginTop:"14px"},text:bodyOf(msg)}))));if(!m.isRead)await updateMailboxMessage(m.id,{isRead:true}).catch(()=>{});}catch(e){detailHost.replaceChildren(emptyState("Lecture impossible",errorMessage(e),"warning"))}};
  const load=async()=>{try{const data=await mailbox(folder,query,"ALL");const messages=data.messages||[];listHost.replaceChildren(toolbar(query,v=>{query=v;load()}),messages.length?h("div",{class:"mail-list"},...messages.map(m=>h("button",{class:`mail-item ${m.isRead?"":"unread"}`,type:"button",onClick:()=>open(m)},h("strong",{text:mailTitle(m)}),h("p",{text:`${sender(m)} · ${bodyOf(m).slice(0,120)}`}),h("p",{text:formatDate(mailDate(m))}))):emptyState("Boîte vide","Aucun message dans ce dossier."));detailHost.replaceChildren(selected?detailHost.firstChild||emptyState("Lecture","Sélectionnez un message."):emptyState("Sélectionnez un message","Le fil complet apparaîtra ici."));}catch(e){listHost.replaceChildren(emptyState("Boîte indisponible",errorMessage(e),"warning"))}};await load();return root;
}
async function templatesView(){const root=h("div");root.append(pageHeader({eyebrow:"E-mails",title:"Modèles",subtitle:"Modèles disponibles pour accélérer les compositions."}));try{const data=await mailboxTemplates();const values=Array.isArray(data)?data:(data.templates||[]);root.append(card("Modèles",`${values.length} modèle${values.length>1?"s":""}.`,values.length?h("pre",{class:"json-view",text:JSON.stringify(values,null,2)}):emptyState("Aucun modèle","Créez vos modèles depuis la boîte mail ou l’app native."),{iconName:"document"}))}catch(e){root.append(emptyState("Modèles indisponibles",errorMessage(e),"warning"))}return root}
async function styleView(){const root=h("div");root.append(pageHeader({eyebrow:"E-mails",title:"Identité & style",subtitle:"Branding centralisé de tous les e-mails Workspace."}));try{const data=await mailboxStyle();const form=h("div",{class:"form"});const controls={};for(const [key,val] of Object.entries(data||{})){if(typeof val==="boolean")controls[key]=h("input",{type:"checkbox",checked:val});else controls[key]=input(val??"");form.append(field(key,controls[key]))}root.append(card("Identité e-mail","Valeurs actives côté serveur.",form,{iconName:"image"}),button("Enregistrer",{kind:"primary",iconName:"check",onClick:async()=>{const next={};for(const [k,el] of Object.entries(controls))next[k]=el.type==="checkbox"?el.checked:el.value;try{await saveMailboxStyle(next);toast("Style e-mail enregistré")}catch(e){toast(errorMessage(e),"error")}}}))}catch(e){root.append(emptyState("Style indisponible",errorMessage(e),"warning"))}return root}
export async function renderMailbox(subpage="mailbox"){if(subpage==="templates")return templatesView();if(subpage==="appearance")return styleView();if(subpage==="connections"){const root=h("div");root.append(pageHeader({eyebrow:"E-mails",title:"Connexion",subtitle:"La connexion Google Workspace est administrée par le backend Squared."}),emptyState("Connexion gérée côté serveur","Les statuts et actions OAuth restent protégés par les routes d’administration mail.","sync"));return root}return mailboxMain()}
