import { state } from "../store.js";
import { loadWorkspace,sendConversationMessage,createConversation,markConversationRead } from "../api.js";
import { h,pageHeader,card,button,modal,field,input,textarea,toast,errorMessage,emptyState,formatDate } from "../ui.js";

function conversationMessages(c){return Array.isArray(c.messages)?c.messages:[]}
function newConversation(reload){const name=input("");const participants=input("",{placeholder:"UUID membre, UUID membre…"});modal({title:"Nouvelle conversation",content:h("div",{class:"form"},field("Nom",name),field("Participants",participants)),actions:[{label:"Créer",kind:"primary",icon:"add",onClick:async close=>{try{const ids=participants.value.split(",").map(x=>x.trim()).filter(Boolean);if(state.user?.id&&!ids.includes(state.user.id))ids.unshift(state.user.id);await createConversation({id:crypto.randomUUID(),name:name.value.trim()||"Nouvelle conversation",participants:[],unread:0,messages:[],participantIDs:ids,kind:ids.length===2?"direct":"team",createdAt:new Date().toISOString()});toast("Conversation créée");close();reload()}catch(e){toast(errorMessage(e),"error",6000)}}}]})}
export async function renderMessages(){
  const root=h("div");let selected=null;const left=h("div"),right=h("div");const reload=async()=>{await loadWorkspace();draw()};
  root.append(pageHeader({eyebrow:"Communication",title:"Messages",subtitle:"Conversations internes synchronisées en temps réel.",actions:[button("Nouvelle conversation",{kind:"primary",iconName:"add",onClick:()=>newConversation(reload)})]}),h("div",{class:"split-view"},card("Conversations","Canaux auxquels vous avez accès.",left,{iconName:"messages"}),card("Discussion","Sélectionnez une conversation.",right,{iconName:"mail"})));
  await loadWorkspace();
  const draw=()=>{const convs=state.workspace?.conversations||[];left.replaceChildren(convs.length?h("div",{class:"mail-list"},...convs.map(c=>h("button",{class:`mail-item ${c.unread?"unread":""}`,type:"button",onClick:()=>open(c)},h("strong",{text:c.name||"Conversation"}),h("p",{text:`${c.participants?.length||c.participantIDs?.length||0} participant(s) · ${conversationMessages(c).length} message(s)`}))):emptyState("Aucune conversation","Créez une conversation avec un membre Workspace."));if(!selected)right.replaceChildren(emptyState("Sélectionnez une conversation","Les messages apparaîtront ici."))};
  const open=async c=>{selected=c;const messages=conversationMessages(c);const messageBox=textarea("",{placeholder:"Écrire un message…"});const thread=h("div",{class:"list"},...(messages.length?messages.map(m=>h("article",{class:"card"},h("div",{class:"row-title",text:m.authorName||m.author||"Membre"}),h("div",{class:"row-sub",text:m.createdAt?formatDate(m.createdAt):m.time||""}),h("div",{class:"mail-body",style:{marginTop:"10px"},text:m.body||""})):[emptyState("Aucun message","Commencez la conversation.")])) ;right.replaceChildren(h("div",{},h("div",{class:"card-head"},h("div",{},h("div",{class:"card-title",text:c.name||"Conversation"}),h("div",{class:"card-subtitle",text:(c.participants||[]).join(" · ")}))),thread,h("div",{class:"form",style:{marginTop:"12px"}},field("Message",messageBox),button("Envoyer",{kind:"primary",iconName:"send",onClick:async()=>{const text=messageBox.value.trim();if(!text)return;try{await sendConversationMessage(c.id,text);messageBox.value="";toast("Message envoyé");await reload();selected=(state.workspace?.conversations||[]).find(x=>x.id===c.id)||c;open(selected)}catch(e){toast(errorMessage(e),"error")}}})));const last=messages.at(-1);markConversationRead(c.id,last?.id||null).catch(()=>{})};
  draw();return root;
}
