import { state,setAppearance } from "../store.js";
import { updateMe,loadSecurity,updateSecurity,changePassword,listSessions,revokeSession,loadSettings,saveSettings,recoveryCodes,createPasskeyOptions,registerPasskey } from "../api.js";
import { createPasskey } from "../webauthn.js";
import { h,pageHeader,card,button,field,input,select,toast,errorMessage,row,emptyState,modal } from "../ui.js";

export async function renderProfile(){
  const u=state.user||{};const root=h("div");root.append(pageHeader({eyebrow:"Compte",title:"Profil",subtitle:"Identité et sécurité de votre compte Squared Workspace."}));
  const email=input(u.email||"",{type:"email"}),first=input(u.firstName||u.first_name||""),last=input(u.lastName||u.last_name||""),title=input(u.title||""),company=input(u.company||""),phone=input(u.phone||"");
  root.append(h("div",{class:"grid two"},card("Identité","Informations visibles selon votre périmètre.",h("div",{class:"form"},h("div",{class:"form-row"},field("Prénom",first),field("Nom",last)),field("E-mail",email),h("div",{class:"form-row"},field("Fonction",title),field("Entreprise",company)),field("Téléphone",phone),button("Enregistrer",{kind:"primary",onClick:async()=>{try{await updateMe({email:email.value,firstName:first.value,lastName:last.value,title:title.value,company:company.value,phone:phone.value,phoneCountryCode:u.phoneCountryCode||u.phone_country_code||"FR"});toast("Profil mis à jour")}catch(e){toast(errorMessage(e),"error")}}})),{iconName:"user"}),await securityCard()));return root;
}
async function securityCard(){
  const host=h("div",{class:"form"});try{let sec=await loadSecurity();const mfa=h("input",{type:"checkbox",checked:sec.multiFactorEnabled}),alerts=h("input",{type:"checkbox",checked:sec.loginAlertsEnabled});host.append(field("Authentification multifacteur",mfa),field("Alertes de connexion",alerts),button("Enregistrer sécurité",{onClick:async()=>{try{sec=await updateSecurity({multiFactorEnabled:mfa.checked,loginAlertsEnabled:alerts.checked});toast("Sécurité mise à jour")}catch(e){toast(errorMessage(e),"error")}}}),button("Ajouter une passkey",{iconName:"key",onClick:async()=>{try{const challenge=await createPasskeyOptions();const response=await createPasskey(challenge.publicKey);await registerPasskey(challenge.challengeId,response,`Web · ${navigator.platform}`);toast("Passkey enregistrée")}catch(e){toast(errorMessage(e),"error",6000)}}}),button("Nouveaux codes de récupération",{onClick:async()=>{try{const data=await recoveryCodes();modal({title:"Codes de récupération",content:h("pre",{class:"json-view",text:JSON.stringify(data,null,2)})})}catch(e){toast(errorMessage(e),"error")}}}),button("Changer le mot de passe",{onClick:()=>passwordModal()}));}catch(e){host.append(emptyState("Sécurité indisponible",errorMessage(e),"warning"))}return card("Sécurité","Passkeys, MFA et récupération.",host,{iconName:"shield"});
}
function passwordModal(){const current=input("",{type:"password"}),next=input("",{type:"password"});modal({title:"Changer le mot de passe",content:h("div",{class:"form"},field("Mot de passe actuel",current),field("Nouveau mot de passe",next)),actions:[{label:"Modifier",kind:"primary",onClick:async close=>{try{await changePassword(current.value,next.value);toast("Mot de passe modifié. Reconnectez-vous sur vos autres appareils.");close()}catch(e){toast(errorMessage(e),"error")}}}]})}

export async function renderSettings(){
  const root=h("div");root.append(pageHeader({eyebrow:"Workspace",title:"Paramètres",subtitle:"Préférences synchronisées entre vos appareils et votre navigateur."}));
  try{let settings=await loadSettings();const theme=select(settings.appearanceMode||"dark",["system","light","dark"]),density=select(settings.dashboardDensity||"Équilibrée",["Aérée","Équilibrée","Dense"]),width=select(settings.contentWidth||"balanced",["focused","balanced","wide"]),language=input(settings.language||"fr-FR"),timezone=input(settings.timezone||"Europe/Paris"),compact=h("input",{type:"checkbox",checked:Boolean(settings.compactSidebar)}),motion=h("input",{type:"checkbox",checked:Boolean(settings.reducedMotion)});
    root.append(card("Apparence & expérience","Les réglages complets restent conservés côté serveur.",h("div",{class:"form"},h("div",{class:"form-row"},field("Thème",theme),field("Densité",density)),h("div",{class:"form-row"},field("Largeur",width),field("Langue",language)),field("Fuseau horaire",timezone),field("Sidebar compacte",compact),field("Réduire les animations",motion),button("Enregistrer",{kind:"primary",onClick:async()=>{try{settings={...settings,appearanceMode:theme.value,dashboardDensity:density.value,contentWidth:width.value,language:language.value,timezone:timezone.value,compactSidebar:compact.checked,reducedMotion:motion.checked};await saveSettings(settings);const effective=theme.value==="system"?(matchMedia("(prefers-color-scheme: light)").matches?"light":"dark"):theme.value;setAppearance({mode:effective});toast("Paramètres enregistrés")}catch(e){toast(errorMessage(e),"error",6000)}}})),{iconName:"settings"}),await sessionsCard());
  }catch(e){root.append(emptyState("Paramètres indisponibles",errorMessage(e),"warning"))}return root;
}
async function sessionsCard(){const host=h("div");try{const sessions=await listSessions();host.append(...(sessions.length?sessions.map(s=>row({title:s.device_name||"Appareil",subtitle:s.platform||"",status:s.id===state.sessionId?"active":"session",meta:new Date(s.last_seen_at||s.created_at).toLocaleString("fr-FR"),actions:[s.id!==state.sessionId?button("Révoquer",{small:true,kind:"ghost",onClick:async()=>{await revokeSession(s.id);toast("Session révoquée")}}):null].filter(Boolean)})):[emptyState("Aucune session","Aucune session active supplémentaire.")]))}catch(e){host.append(emptyState("Sessions indisponibles",errorMessage(e),"warning"))}return card("Sessions actives","Révoquez un navigateur ou appareil que vous ne reconnaissez pas.",host,{iconName:"lock"})}
