import { trainingCatalog,trainingLesson,setTrainingProgress } from "../api.js";
import { h,pageHeader,card,row,button,modal,emptyState,toast,errorMessage,badge } from "../ui.js";
export async function renderTraining(){
  const root=h("div");root.append(pageHeader({eyebrow:"Squared BUILD",title:"Formation",subtitle:"Votre parcours, vos leçons et votre progression synchronisés avec le CMS Squared."}));
  try{let catalog=await trainingCatalog();const stats=catalog.stats||{};root.append(h("div",{class:"grid stats"},...[["Modules",stats.modules||0],["Leçons",stats.lessons||0],["Accessibles",stats.accessibleLessons||0],["Terminées",stats.completedLessons||0]].map(([l,v])=>h("div",{class:"card"},h("div",{class:"stat-value",text:String(v)}),h("div",{class:"stat-label",text:l}))));
    const host=h("div",{class:"list"});root.append(card(catalog.program?.title||"Programme BUILD",catalog.program?.description||"Programme de formation Squared.",host,{iconName:"star"}));
    const redraw=()=>{host.replaceChildren(...((catalog.lessons||[]).map(lesson=>row({title:`${lesson.code?lesson.code+" · ":""}${lesson.title}`,subtitle:lesson.summary||lesson.learningObjective,status:lesson.isCompleted?"completed":lesson.isUnlocked?"active":"locked",meta:lesson.readingMinutes?`${lesson.readingMinutes} min`:"",actions:[button("Ouvrir",{small:true,disabled:!lesson.isUnlocked,onClick:async()=>{try{const detail=await trainingLesson(lesson.id);const content=h("div",{},h("p",{class:"page-subtitle",text:lesson.learningObjective||lesson.summary||""}),h("pre",{class:"json-view",text:typeof detail.content==="string"?detail.content:JSON.stringify(detail.content,null,2)}));modal({title:lesson.title,content,wide:true,actions:[{label:lesson.isCompleted?"Marquer à refaire":"Marquer terminée",kind:"primary",onClick:async close=>{try{catalog=await setTrainingProgress(lesson.id,!lesson.isCompleted);toast("Progression enregistrée");close();redraw()}catch(e){toast(errorMessage(e),"error")}}}]})}catch(e){toast(errorMessage(e),"error")}}})]}))));};redraw();
  }catch(e){root.append(emptyState("Formation indisponible",errorMessage(e),"warning"))}return root;
}
